# Generated by Django 2.0.13 on 2021-01-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=200)),
                ('kind', models.CharField(help_text='종류', max_length=200)),
                ('desc', models.TextField(help_text='개발툴 설명')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='아이디어명', max_length=200)),
                ('image', models.ImageField(help_text='대표 사진', upload_to='idea_site_image/%Y/%m/%d/')),
                ('content', models.TextField(help_text='아이디어 설명')),
                ('interest', models.IntegerField(help_text='아이디어 관심도')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('devtool', models.ForeignKey(help_text='예상 개발툴', on_delete=django.db.models.deletion.CASCADE, related_name='idea', to='page.Devtool')),
            ],
        ),
    ]
